--- #YAML:1.0
name: Javascript-MD5
version: 1.02
author:
  - Ron Savage <ron@savage.net.au>
abstract: Calculate the MD5 digest of a CGI form field
license: artistic
provides: {}
generated_by: Module::Build version 0.24
