--- #YAML:1.0
name: Javascript-MD5
version: 1.05
author:
  - Ron Savage <ron@savage.net.au>
abstract: Calculate the MD5 digest of a CGI form field
license: artistic
build_requires:
  Test::More: 0
  Test::Pod: 0
provides:
  Javascript::MD5:
    file: lib/Javascript/MD5.pm
    version: 1.05
generated_by: Module::Build version 0.2611
